### PR TITLE
Changing Unity location detection to work with all windows/java bitness combos.

### LINKED ISSUE #21: Won't find unity install on windows
The plugin fails to find my install of unity on a windows build agent. By the looks of things it has something to do with me running 32-bit java on 64-bit windows with 64-bit unity.

Will investigate further.

### PR DESCRIPTION
**Pull request by MitchellLawson-Burton**
Fixes #21.

### CODE REVIEW

**Comment by Belorus** [comment]
Great PR. Please merge it to master.

**Comment by headfirstdive** [comment]
Can we get this merged into master already?
Or at least a pre-built version of this PR?

**Comment by MitchellLawson-Burton** [comment]
Moved to #30 so I can clean up branches.

**Comment by MitchellLawson-Burton** [comment]
Also, prebuilt version of the PR: https://github.com/MitchellBurton/Teamcity-unity3d-build-runner-plugin/releases/tag/v0.1

**Pull request closed without merging**
